/*
 Navicat Premium Data Transfer

 Source Server         : PosgreSql@localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : localhost:5432
 Source Catalog        : MailService
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 02/08/2024 11:52:45
*/


-- ----------------------------
-- Sequence structure for EmailProviders_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."EmailProviders_id_seq";
CREATE SEQUENCE "public"."EmailProviders_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for OtpRequests_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."OtpRequests_Id_seq";
CREATE SEQUENCE "public"."OtpRequests_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for SmsMessageLogs_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."SmsMessageLogs_Id_seq";
CREATE SEQUENCE "public"."SmsMessageLogs_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for SmsMessages_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."SmsMessages_Id_seq";
CREATE SEQUENCE "public"."SmsMessages_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for SmsProviderDevices_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."SmsProviderDevices_Id_seq";
CREATE SEQUENCE "public"."SmsProviderDevices_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for SmsProviders_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."SmsProviders_Id_seq";
CREATE SEQUENCE "public"."SmsProviders_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for api_key_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."api_key_id_seq";
CREATE SEQUENCE "public"."api_key_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for email_template_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."email_template_id_seq";
CREATE SEQUENCE "public"."email_template_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for otp_card_tokens_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."otp_card_tokens_id_seq";
CREATE SEQUENCE "public"."otp_card_tokens_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for otp_cards_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."otp_cards_id_seq";
CREATE SEQUENCE "public"."otp_cards_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for otp_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."otp_id_seq";
CREATE SEQUENCE "public"."otp_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for queue_message_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."queue_message_id_seq";
CREATE SEQUENCE "public"."queue_message_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for OtpRequests
-- ----------------------------
DROP TABLE IF EXISTS "public"."OtpRequests";
CREATE TABLE "public"."OtpRequests" (
  "Id" int8 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "Code" text COLLATE "pg_catalog"."default",
  "Mobile" varchar(12) COLLATE "pg_catalog"."default",
  "VerifyRequestId" text COLLATE "pg_catalog"."default",
  "Type" int4 NOT NULL,
  "NumVerify" int4 NOT NULL,
  "Status" int4 NOT NULL,
  "SentTime" timestamp(6) NOT NULL,
  "CreatedTime" timestamp(6) NOT NULL,
  "ExpiredTime" timestamp(6) NOT NULL,
  "VerifiedTime" timestamp(6),
  "NumVerifyMax" int4 NOT NULL,
  "ResendRemain" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for SmsMessageLogs
-- ----------------------------
DROP TABLE IF EXISTS "public"."SmsMessageLogs";
CREATE TABLE "public"."SmsMessageLogs" (
  "Id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "CreateTime" timestamp(6) NOT NULL,
  "SmsMessageId" int8 NOT NULL,
  "Request" jsonb,
  "Response" jsonb,
  "ProviderId" int8,
  "ProviderResponseCode" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for SmsMessages
-- ----------------------------
DROP TABLE IF EXISTS "public"."SmsMessages";
CREATE TABLE "public"."SmsMessages" (
  "Id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "RequestId" text COLLATE "pg_catalog"."default",
  "Date" int4 NOT NULL,
  "CreateTime" timestamp(6) NOT NULL,
  "SmsProviderId" int4 NOT NULL,
  "SmsTemplateId" int4,
  "Data" jsonb,
  "Message" text COLLATE "pg_catalog"."default",
  "ClientId" text COLLATE "pg_catalog"."default",
  "Status" int4 NOT NULL,
  "ReTryTimes" int4,
  "SendTime" timestamp(6),
  "PhoneNumber" text COLLATE "pg_catalog"."default",
  "SmsClientPhoneNumber" varchar(255) COLLATE "pg_catalog"."default",
  "Subject" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for SmsProviderDevices
-- ----------------------------
DROP TABLE IF EXISTS "public"."SmsProviderDevices";
CREATE TABLE "public"."SmsProviderDevices" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "DeviceId" varchar(32) COLLATE "pg_catalog"."default",
  "SecretKey" varchar(255) COLLATE "pg_catalog"."default",
  "PhoneNumber" varchar(50) COLLATE "pg_catalog"."default",
  "TelecomType" varchar(255) COLLATE "pg_catalog"."default",
  "AreaCode" varchar(255) COLLATE "pg_catalog"."default",
  "SmsProviderId" int4
)
;

-- ----------------------------
-- Table structure for SmsProviders
-- ----------------------------
DROP TABLE IF EXISTS "public"."SmsProviders";
CREATE TABLE "public"."SmsProviders" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Name" text COLLATE "pg_catalog"."default",
  "ProviderConnectConfig" jsonb,
  "Status" int4 NOT NULL,
  "CreateDate" timestamp(6),
  "UpdateDate" timestamp(6)
)
;

-- ----------------------------
-- Table structure for SmsTemplates
-- ----------------------------
DROP TABLE IF EXISTS "public"."SmsTemplates";
CREATE TABLE "public"."SmsTemplates" (
  "Id" int4 NOT NULL,
  "Name" text COLLATE "pg_catalog"."default",
  "Template" text COLLATE "pg_catalog"."default" NOT NULL,
  "VariableFields" text COLLATE "pg_catalog"."default",
  "Status" int4 NOT NULL,
  "Campaign" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for clients
-- ----------------------------
DROP TABLE IF EXISTS "public"."clients";
CREATE TABLE "public"."clients" (
  "id" int4 NOT NULL DEFAULT nextval('api_key_id_seq'::regclass),
  "client_id" varchar(255) COLLATE "pg_catalog"."default",
  "client_secret" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "hash_token" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for email_templates
-- ----------------------------
DROP TABLE IF EXISTS "public"."email_templates";
CREATE TABLE "public"."email_templates" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "template" text COLLATE "pg_catalog"."default",
  "variable_fields" text COLLATE "pg_catalog"."default",
  "is_active" bool,
  "campaign" varchar(50) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for mail_providers
-- ----------------------------
DROP TABLE IF EXISTS "public"."mail_providers";
CREATE TABLE "public"."mail_providers" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "provider_config" text COLLATE "pg_catalog"."default",
  "status" varchar(10) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for otp
-- ----------------------------
DROP TABLE IF EXISTS "public"."otp";
CREATE TABLE "public"."otp" (
  "id" int8 NOT NULL DEFAULT nextval('otp_id_seq'::regclass),
  "tracking_id" text COLLATE "pg_catalog"."default",
  "client" varchar(20) COLLATE "pg_catalog"."default",
  "otp_type" varchar(20) COLLATE "pg_catalog"."default",
  "otp_code" varchar(6) COLLATE "pg_catalog"."default",
  "max_retry" int4,
  "retry_count" int4,
  "max_resend" int4,
  "resend_count" int4,
  "send_info" text COLLATE "pg_catalog"."default",
  "status" varchar(10) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "expiring_time" timestamp(6),
  "hash_token" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for otp_card_tokens
-- ----------------------------
DROP TABLE IF EXISTS "public"."otp_card_tokens";
CREATE TABLE "public"."otp_card_tokens" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "card_serial" varchar(20) COLLATE "pg_catalog"."default",
  "position" int4,
  "token" varchar(6) COLLATE "pg_catalog"."default",
  "hash_token" text COLLATE "pg_catalog"."default",
  "create_at" timestamp(6),
  "otp_card_id" int8
)
;

-- ----------------------------
-- Table structure for otp_cards
-- ----------------------------
DROP TABLE IF EXISTS "public"."otp_cards";
CREATE TABLE "public"."otp_cards" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8,
  "card_serial" varchar(20) COLLATE "pg_catalog"."default",
  "published_at" timestamp(6),
  "issue_at" timestamp(6),
  "expire_at" timestamp(6),
  "status" varchar(10) COLLATE "pg_catalog"."default",
  "hash_token" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for queue_messages
-- ----------------------------
DROP TABLE IF EXISTS "public"."queue_messages";
CREATE TABLE "public"."queue_messages" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "tracking_id" text COLLATE "pg_catalog"."default",
  "client" varchar(50) COLLATE "pg_catalog"."default",
  "data" text COLLATE "pg_catalog"."default",
  "to_address" varchar(50) COLLATE "pg_catalog"."default",
  "subject" varchar(255) COLLATE "pg_catalog"."default",
  "email_template" varchar(20) COLLATE "pg_catalog"."default",
  "message_sent" bool,
  "from_address" varchar(50) COLLATE "pg_catalog"."default",
  "sender_name" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."EmailProviders_id_seq"
OWNED BY "public"."mail_providers"."id";
SELECT setval('"public"."EmailProviders_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."OtpRequests_Id_seq"
OWNED BY "public"."OtpRequests"."Id";
SELECT setval('"public"."OtpRequests_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."SmsMessageLogs_Id_seq"
OWNED BY "public"."SmsMessageLogs"."Id";
SELECT setval('"public"."SmsMessageLogs_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."SmsMessages_Id_seq"
OWNED BY "public"."SmsMessages"."Id";
SELECT setval('"public"."SmsMessages_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."SmsProviderDevices_Id_seq"
OWNED BY "public"."SmsProviderDevices"."Id";
SELECT setval('"public"."SmsProviderDevices_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."SmsProviders_Id_seq"
OWNED BY "public"."SmsProviders"."Id";
SELECT setval('"public"."SmsProviders_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."api_key_id_seq"
OWNED BY "public"."clients"."id";
SELECT setval('"public"."api_key_id_seq"', 15, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."email_template_id_seq"
OWNED BY "public"."email_templates"."id";
SELECT setval('"public"."email_template_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."otp_card_tokens_id_seq"
OWNED BY "public"."otp_card_tokens"."id";
SELECT setval('"public"."otp_card_tokens_id_seq"', 2205, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."otp_cards_id_seq"
OWNED BY "public"."otp_cards"."id";
SELECT setval('"public"."otp_cards_id_seq"', 63, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."otp_id_seq"
OWNED BY "public"."otp"."id";
SELECT setval('"public"."otp_id_seq"', 40, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."queue_message_id_seq"
OWNED BY "public"."queue_messages"."id";
SELECT setval('"public"."queue_message_id_seq"', 86, true);

-- ----------------------------
-- Primary Key structure for table clients
-- ----------------------------
ALTER TABLE "public"."clients" ADD CONSTRAINT "api_key_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table email_templates
-- ----------------------------
ALTER TABLE "public"."email_templates" ADD CONSTRAINT "email_template_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table mail_providers
-- ----------------------------
ALTER TABLE "public"."mail_providers" ADD CONSTRAINT "EmailProviders_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table otp
-- ----------------------------
CREATE INDEX "idx_tracking_id" ON "public"."otp" USING btree (
  "tracking_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table otp
-- ----------------------------
ALTER TABLE "public"."otp" ADD CONSTRAINT "otp_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table otp_card_tokens
-- ----------------------------
ALTER TABLE "public"."otp_card_tokens" ADD CONSTRAINT "otp_card_tokens_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table otp_cards
-- ----------------------------
ALTER TABLE "public"."otp_cards" ADD CONSTRAINT "otp_cards_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table queue_messages
-- ----------------------------
ALTER TABLE "public"."queue_messages" ADD CONSTRAINT "queue_message_pkey" PRIMARY KEY ("id");
